7 create photo container
dcTeam7/students-dashboard pull request #8
Opened 2022-11-09 04:14 UTC by gabrielapcustodio

Create container and photo #7

2022-11-09 15:48 UTC, joellacerda approved these changes
Acho que o tamanho do container da imagem ficou bom, mas vamos ter uma noção melhor quando adicionarmos a plaquinha com o nome do estudante. Por enquanto, approved.

2022-11-09 15:56 UTC, joellacerda requested changes
Depois que dei uma olhada melhor, acho melhor fazer essas alterações na class .container do arquivo .css:

```
.container {
   position: relative;
   top: -30px;
   left: 15px;
}
```

Antes o container estava como `position: absolute`, mas isso faria com que a imagem ficasse posicionada em relação à tela, e não ao card. Com o `position: relative`, ele ficará agora posicionado em relação ao card. As alterações no top e no left são para posicionar melhor o container.

2022-11-09 16:04 UTC, Deborahhm commented on styles.css
> +  content: " ";
O tamanho do container e os efeitos ficaram muito bons, mas concordo com joel sobre o posicionamento

2022-11-10 01:15 UTC, gabrielapcustodio commented
Massa, gente! Obrigada pelo retorno. Mudanças feitas. :)

2022-11-11 12:27 UTC, joellacerda approved these changes

2022-11-12 14:30 UTC, merged